### ISSUE TITLE
NIVIDA TX2 NX installation failed

### ISSUE THREAD

**Issue by Guangday** [stephendade/Rpanion-server#183] opened 2023-12-11 14:33 UTC
An error occurred while installing rpanion-server into nivida tx2 nx. install_common_libraries.sh terminates running, as shown below.
Run：pip3 install --upgrade pymavlink --user --break-system-packages
Q：no such option: --break-system-packages

**Comment by stephendade** [comment] 2023-12-11 21:48
What Ubuntu version and pip version are you using?

**Comment by Guangday** [comment] 2023-12-12 01:26
Ubuntu 18.046LTS，pip 21.3.1;

**Comment by stephendade** [comment] 2023-12-12 03:04
I've confirmed the bug. Fix is in #184. Thanks for reporting!

> If I am trying to modify rpanion-server on ubuntu, is there any recommended engineering compiler?

Rpanion-server is written in nodejs, as such there's no compiler required. Just the nodejs runtime.

**Comment by Guangday** [comment] 2023-12-12 04:40
There is also a problem, I installed the system using the NIVIDA official SDKmaneger, and the following error occurs in the command sudo apt install -y nodejs. My system didn't change any of the source files, and there may be other people who made the same mistake as me.
nodejs: Dependency: libc6 (>= 2.28) But 2.27-3ubuntu1.6 is being installed
E: You can't fix the bug because you require certain packages to remain as they are, which breaks the dependencies between packages.

**Comment by Guangday** [comment] 2023-12-12 06:44
I have found the cause of the problem. It is indicated in the official website file that ubuntu18 no longer supports npm and later versions. I hope you can mark it.
![Uploading 屏幕截图 2023-12-12 144357.png…]()

**Comment by Guangday** [comment] 2023-12-12 06:45
I have found the cause of the problem. It is indicated in the official website file that ubuntu18 no longer supports npm and later versions. I hope you can mark it.
![Uploading 2023-12-12 144357.png…]()

**Comment by stephendade** [comment] 2023-12-12 11:26
Ok, looks like Ubuntu 18 supports nodejs16 at the latest. I'll edit the scripts to use v18 instead of v20 - now in #185

**Closed** 2023-12-12 13:45 UTC
